version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8090:5000"  # Map host port 8090 to container port 5000
    depends_on:
      - db
    environment:
      FLASK_APP: app:create_app  # Specify the Flask app
      FLASK_RUN_PORT: 5000
      FLASK_ENV: development
      DATABASE_URL: postgresql://sa:Your_password123@db:5432/MovieSalesDb
    volumes:
      - ./:/app  # Map local `app` directory to `/app` in the container
      - /app/__pycache__/  # Optional: Prevent caching in the container

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: Your_password123
      POSTGRES_DB: MovieSalesDb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  app-data:
  db-data:
